### ISSUE TITLE
Should we allow 360 as a valid azimuth value?

### ISSUE THREAD

**Issue by SCEDC** [FDSN/StationXML#11]
Hi  - we have some records with azimuth values of 360.  According to the SEED manual p68:

"Traditionally, the mass (boom) on vertical seismometers is oriented to the north, but sometimes this is not possible. If you know the vertical orientation, place it in the azimuth field. If the orientation is 0 degrees, use an azimuth of 360.0. If you do not know the orientation, set the azimuth to 0.0.”

Can we change the schema to permit 360 as value -- currently it is excluded.

**Comment by chad-iris** [comment]
I would think we do not want to allow azimuth values of 360.  That is a kludge in the SEED header format for distinguishing between a known versus unknown value for a field that must be present.  Whereas in StationXML the azimuth is optional and can be left out if it is not known.

The IRIS DMC's StationXML converter will map the StationXML usage to/from SEED headers as described here:
https://seiscode.iris.washington.edu/issues/808
