### ISSUE TITLE
invisible example of ODD/EVEN/NONE

### ISSUE THREAD

**Issue by PetrColinSky** [FDSN/StationXML#129]
I can't see the example which @jschaeff added for the symmetry of filters. It is not here:
file:///D:/35fdsn/StationXML-01-26doc_issues/docs/_build/html/response.html
and when I try to build the html locally, i got the following warning from sphinx:

transform-FIR-IIR.rst:345: WARNING: Unknown directive type "xml"
meaning, that command
<code>
.. xml::
</code>
is the troublemaker.
See line 345 in the file "transform-FIR-IIR.rst".

**Comment by crotwell** [comment]
Just pushed a fix, 6f9ec58 that uses `code-block:: XML` that seems to work.

@PetrColinSky can you verify?

**Comment by PetrColinSky** [comment]
Works! Beautiful! No warning, nice output, thanks.
The link in my previous post was obviously wrong, pointing to my local file, should have been
https://docs.fdsn.org/projects/stationxml/en/doc_issues/response.html
where it looks beautiful now as well.
