### ISSUE TITLE
mandatory gain stage for  polynomial response

### ISSUE THREAD

**Issue by lemarchandarnaud** [FDSN/StationXML#13]
Dear all

I convert dataless SEED in StationXML with the java tool of iris : stationxml-converter-1.0.9.jar. When I check the consistency of the StationXML with its schema (http://www.fdsn.org/xml/station/fdsn-station-1.0.xsd),  I can see erros in polynomial responses because a Stagegain is mandatory (<xs:element name="StageGain" type="fsx:GainType">).
It doesn't really make sense to me to add a StageGain to a polynomial response. What is the movivation for that?
I am wandering if  it is a bug  because the documention tell us 
> This complex type represents channel response and covers SEED blockettes 53 to 56 

 thougth this is  the blockette 62 which describes polynomial reponses.  
Thus the polynomial response may have been added in the schema without entertainning this difficulty?

many thanks for your answers
arnaud lemarchand
volcano observatories of IPGP
France

**Comment by chad-iris** [comment]
Dear arnaud lemarchand,

I believe this is an error in the schema that is addressed in PR #2.  I assume it will be approved for inclusion into the next version of the schema.

**Comment by lemarchandarnaud** [comment]
Dear Chad
Thanks for you answer. Do you know when the version will  be release. This issue has been  known for 2 years ( at least) and I guess it will take time. I may have to find a temporary solution as this issue blocks the insertion of my StationXML file in Seiscomp3.

**Comment by crotwell** [comment]
I can't remember if I fully addressed this issue but you could try
validating against this instead of the official stationxml schema:
https://github.com/crotwell/QuirksStationXML

Philip

**Comment by crotwell** [comment]
I believe this is fixed in d1422b685e7086445e4024071f71cae139b4ba16 that was part of ver 1.1 and so can be closed.
