### ISSUE TITLE
spell check

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#141]
I figured out how to run sphinxcontrib-spelling to spell check the .rst files. There were A LOT OF MISTAKES!

Spell check now passes with no mispellings. The convert script now builds docs/spelling/schema_words.txt so the the element and attribute names are whitelisted. 

Also, there were some words that should be ok, in a separate file, docs/spelling/text_words.txt. I think these are ok, but might be good if someone else can have a quick look at them.

PR #140 has all the fixes and the spelling files. Also updated readme and conf.py. Note spelling in extensions is currently commented out as figured not everyone would install this.

**Comment by PetrColinSky** [comment]
Wow, really nice that spelling thing. I have checked the words in docs/spelling/text_words.txt.

Does the word "desampling" exist? I know "downsampling", meaning "to lower the number of samples", but "desampling" sounds like "removing sampling".

The abbreviation "dsp" is not explained. Should be "digital signal processing", probably. The abbreviation is used only once, so no need for abbreviating. It is in the same sentence as "desampling" (3.1.4 FIR-IIR Filters - Practical concerns).

"nyquist" should be maybe "Nyquist" everywhere.

The meaning of "pn" is not clear to me (3.3.7. Setra 270 example, see the second table).

There are various versions of the same term, e.g.: "pre-amplifier" / "preamplifier" / "pre-amp".

**Comment by crotwell** [comment]
Good points. Updated so:
desampling -> downsampling
dsp -> digital signal processing
nyquist -> Nyquist
various pre-amp -> preamplifier

I also don't really get the pn in the Setra example either. I presume it is supposed to mean "polynomial"? Perhaps just changing it to "p(volts)" to indicate it is a function of volts.

All pushed to the PR. Thanks.

**Comment by jschaeff** [comment]
Brilliant !
