### ISSUE TITLE
FIR and Coefficients, asymetric filter

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#147]
I think this line, in section 3.1.4, in "Classification of FIR filters" is wrong.

> In contrast, a non-symmetrical FIR can only be stored in a more general Coefficients response stage, which retains all of the coefficients.

Isn't a non-symmetrical FIR filter the same as FIR with symmety=None, which stores all the coefficients? I don't see why asymmetry implies you have to use Coefficients type? If you have a non-finite response filter, then you have denominators and so have to use Coefficients, but as long as it is finite, the FIR filter type should be used.

@chad-iris or @mikehagerty can you comment?

**Comment by crotwell** [comment]
removed this sentence in beaf741

**Comment by crotwell** [comment]
commit is also in PR #148

**Comment by mikehagerty** [comment]
I agree - I think you can store a non-symmetric FIR with symmetry=None but
giving all the coefficients as Philip suggests.

I guess a question for Chad/IRIS is: Are there any examples of this ?   or
is it just a holdover from SEED that we're preserving ?

-Mike

**Comment by chad-iris** [comment]
Yeah, I think it was just wrong.  There are not many (any?) examples of this because the overwhelming usage is for FIR to be expressed in a Coefficients structure instead of FIR.  Not sure it matters, the ability to express FIRs in two different structures exists in both SEED and StationXML.
