### ISSUE TITLE
Equipment in Channel should have maxOccurs="unbounded" like in Station

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#15]
Station has Equipment as a subelement with 
`minOccurs="0" maxOccurs="unbounded"`

But in Channel, the Equipment subelement only has 
`minOccurs="0"`
which makes it zero or one.

The purpose of the Equipment is to allow information about hardware that may be associated with the Channel, but does not fit into the other catagories (Sensor, PreAmplifies, DataLogger). There could be multiple pieces of Equipment, and so this should be allowed to be more than one.

**Comment by megies** [comment]
I believe this made it into 1.1? Maybe the ticket should be milestoned and closed?
