### ISSUE TITLE
Two different coordinates for one station

### ISSUE THREAD

**Issue by chemarev** [FDSN/StationXML#153]
Hi there! Could you recommend how to solve the following question? I have one station with two different coordinates in different periods. I know about a recommendation that if the station was moved more than 500 meters, it should have a new name. But for that station, it is a part of history already. I am puzzled how to form StationXML in situation when the channel request is received. I see two ways: 1) to form one `<Station>` block with actual coordinates, and put non-actual to `<Comment>` section. 2) to form two <Station> blocks, one with `"endDate"` attribute for the non-actual coordinates, another without `"endDate"` for the actual coordinates. But I don't know is it correct to have two `<Station>` block with the same station name.

**Comment by megies** [comment]
You definitely want to have two separate Station blocks with one being closed at the time of change and the other one opening at that time.

**Comment by rcasey-iris** [comment]
Hi Andrew-

	Could you point to the source that indicates that the station needs to be renamed when it is moved more than 500m?  I know in the old days, station naming was based on a square kilometer area, but I am not sure that still applies these days.  I'm not saying it's not the rule, but I also don't know where the current literature is on the matter.

	-Rob

**Comment by chemarev** [comment]
> You definitely want to have two separate Station blocks with one being closed at the time of change and the other one opening at that time.

@megies Thanks a lot! I will go this way.

**Comment by chemarev** [comment]
> Hi Andrew- Could you point to the source that indicates that the station needs to be renamed when it is moved more than 500m? I know in the old days, station naming was based on a square kilometer area, but I am not sure that still applies these days. I'm not saying it's not the rule, but I also don't know where the current literature is on the matter. -Rob

Hello, Rob! Ow, yeah, you are right. The numbers mixed in my head. That recommendation says about 1 km distance. It is contained in the implementation of the new IASPEI station coding standard (available at [this link from ISC website](http://www.isc.ac.uk/registries/download/IR_implementation.pdf)) and also at their [station registration page](http://www.isc.ac.uk/registries/registration/). Thanks for the notice, I will remember right distance better.
