### ISSUE TITLE
FDSN DOI lookup tool acting weird

### ISSUE THREAD

**Issue by megies** [FDSN/StationXML#28]
This is likely not the right place to report this, but I don't know where else to put it.

The network citation lookup tool gives really weird output in some cases, even for network DOIs minted directly on FDSN web site:

![Screenshot from 2020-07-24 18-11-28](https://user-images.githubusercontent.com/1842780/88411968-2163b000-cdd9-11ea-9a15-d2b1da6769ad.png)
![Screenshot from 2020-07-24 18-11-14](https://user-images.githubusercontent.com/1842780/88411975-2294dd00-cdd9-11ea-84f7-62fe00039cc5.png)

CC @jwassermann

**Comment by chad-iris** [comment]
Forwarded to webmaster <at> fdsn.org

**Comment by adam-iris** [comment]
This should be fixed, "Earth, D. O." is how DataCite displays "Department Of Earth And Environmental Sciences, Geophysical Observatory, University Of Munchen" if it's mistakenly labeled as a personal name.

**Comment by megies** [comment]
Thank you, can confirm it's fixed.
