### ISSUE TITLE
indentation to indicate subelements

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#41]
The only indication in the docs that something is a subelement of something above it is the lack of the section number in front of it. And for sub-sub elemnts there really isn't anything.

Some kind of indentation, or containment box so it is visually easy to see what is contained in what would be useful.

Good example is `Station → Operator → Contact → Phone → PhoneNumber` which is followed by `Station → Operator → WebSite`. Visually they look like they are on the same level, but PhoneNumber is 3 levels down in the hierarchy.

**Comment by crotwell** [comment]
I see now that the nav bar on the left shows the hierarchy as you scroll down, which is cute. I like it.

However, I still feel like the documentation for each element is missing at least the emphasis on the child elements that can be contained within it, and their cardinality. And the nav bar on the left does not show that Network is contained in FDSNStationXML, nor that Station is contained in Network nor that Response is contained in Channel.

Perhaps would be good to list the child elements within the each element's box, along with their cardinality.

**Comment by crotwell** [comment]
fixed in PR #88

**Comment by jschaeff** [comment]
It could be nice to see the HTML rendered doc with this feature.
