### ISSUE TITLE
is Channel -> Type meaningful

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#44]
[Channel → Type](http://docs.fdsn.org/projects/stationxml/en/draft/reference.html#channel-type) seems to be a bucket to put something that exists in SEED, but isn't really meaningful anymore. It more or less duplicates the information in the channel instrument code from what I can tell. 

Perhaps should consider either removing this, or making it more meaningful.

**Comment by crotwell** [comment]
Is there any reason to keep this?

Propose to document not to use this element and that this may be removed in next version.

**Comment by chad-iris** [comment]
I believe the purpose of this as a general category is minimally useful, and mostly supplanted by the more-specific channel designation.  I'd support marking it as legacy, do-not-use.

**Comment by crotwell** [comment]
PR #125

**Comment by crotwell** [comment]
fix in #125
