### ISSUE TITLE
resourceId in InstrumentPolynomial refers to equipment

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#45]
The description of the `resourceId` attribute of [InstrumentPolynomial](http://docs.fdsn.org/projects/stationxml/en/draft/reference.html#instrumentpolynomial) looks like it was copied from equipment, but doesn't make sense in here.

> It should be expected that equipment with the same ID should indicate the same information/be derived from the same base instruments.

Also same in Stage

**Comment by crotwell** [comment]
fixed in #81

**Comment by crotwell** [comment]
Something looks fishy here, I may have created the PR from the wrong branch (master instead of docissues). I'll look into it before we merge.

**Comment by PetrColinSky** [comment]
Many commits in PR #81  are contained also in other PRs, like "remove leveldefault" is solved in PR #80, "make Warning: into <warning> element" is in PR #72 and so on.
