### ISSUE TITLE
examples in docs should use SI units

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#46]
stationxml examples often use all caps units, but docs also say SI units are preferred. Better if the examples follow the SI standard where possible.

Example [accelerometer response](http://docs.fdsn.org/projects/stationxml/en/draft/response.html#accelerometer):
```
            <InputUnits>
              <Name>M/S**2</Name>
              <Description>Acceleration in Meters Per Second Per Second</Description>
            </InputUnits>
```
should be lower case `m/s**2` instead.

**Comment by crotwell** [comment]
fixed in PR #84 and PR #83

**Comment by WayneCrawford** [comment]
The [documentation of the "Description" element](https://docs.fdsn.org/projects/stationxml/en/latest/reference.html#channel-calibrationunits-description) still gives non-recommended examples such as "Velocity in meters per second" and "Pascals".

Also, non-recommended Descriptions are shown in the [StationXML Response Examples](https://docs.fdsn.org/projects/stationxml/en/latest/response.html#stationxml-response-examples).  For example, for the "Broadband Sensor" you still have:

```xml
        <Response>
          <InstrumentSensitivity>
            <Value>941864732.693</Value>
            <Frequency>1.0</Frequency>
            <InputUnits>
              <Name>m/s</Name>
              <Description>Velocity in Meters per Second</Description>
            </InputUnits>
            <OutputUnits>
              <Name>count</Name>
              <Description>Digital Counts</Description>
            </OutputUnits>
```

**Comment by crotwell** [comment]
Can you open a new issue and reference this one? This issue was the actual units being SI, and seems like you are referencing the description of the units. Thanks.
