### ISSUE TITLE
prefer singluar lower case 'count' instead of COUNT, counts or COUNTS

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#50]
Given the volume of historical metadata, we will have to live with all the variations of `count`, but now would be a good time to establish that the singular, lowercase `count` is the preferred unit for digitized data. SI units are singular, and case sensitive, and so I think `count` is the most consistent value. What is put in the documentation will guide people going forward, and so we should give a nudge in the direction of consistency.

Would be good if all count unit examples were given in singular lower case.

Perhaps also adding something to [section 5.4 ](http://docs.fdsn.org/projects/stationxml/en/draft/appendices.html#unit-naming-rules) would help standardize this.

**Comment by megies** [comment]
Did not follow all discussions and developments but just in case compare iris-edu/stationxml-validator#94

**Comment by crotwell** [comment]
Yes, good context. 

Note I was not proposing to disallow COUNT or counts or COUNTS. Just that there should be one variant that is preferred and the documentation should use it. I think lowercase singular makes the most sense.

**Comment by crotwell** [comment]
fix in #115
