### ISSUE TITLE
document endDate for net, station or channel still active

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#57]
Historically SEED used a date far in the future, like 2500-01-01, to indicate a active network, station or channel. In stationxml since the endDate attribute is optional, it is better to indicate something is still active by not having an endDate attribute rather than picking a future date. Docs should make this clear.

**Comment by crotwell** [comment]
fixed in #78

**Comment by jschaeff** [comment]
That's a must !

**Comment by PetrColinSky** [comment]
The best is, when someone sets a date in 2-yrs future for the temporary station which is planned to be deployed for 2 yrs, and then the station is left there for longer ... I know examples like this. You get data which is outside of a valid response epoch.
