### ISSUE TITLE
Clarifications within the <Stage> level

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/StationXML#60]
We are working on software to create StationXML files for ocean-bottom seismometer deployments.  This work is in close collaboration with the new Atomic Response Object Library (AROL), and we dig deep into StationXML definitions.  We are happy to see the StationXML documentation project and would like to offer a few questions about what we think are ambiguities in the present documentation. 

All of our questions are beneath the `<Stage>` level:
### `<PoleZeros><Normalization Frequency>` 
The documentation says "should be the same for all stages and within the passband, if any"
Do you mean for all `<PoleZeros>` stages? (these are the only ones I know of with a `<NormalizationFrequency>`) or do you also include `<StageGain><Frequency>`s?  

### `<StageGain><Frequency>`: 
There is no mention of a requirement for all `<StageGain>` frequencies to be equal: is this the case.  Also, can `<Frequency> = 0`  be used for stages whose gain does not vary with frequency (this seems to be common usage)?

### `<Decimation><Offset>`,  `<Delay>` and `<Correction>`:
Our instruments correct the digital stages' delay at the software level.  How should this be entered?   We currently set `<Correction> = 0` at all levels except the last, in which we put the entire correction value

How is `<Delay>` related to `<Offset>`?  In the simplest cases, I would imagine that `<Delay>` = `<Offset> / <InputSampleRate>`, but I can imagine that for additional analog delays this would be otherwise. It would be nice if this were clarified.

### Stages without a filter
How does one enter a stage without a filter? (pure amplifier, either on analog or digital end).  Currently, I use:
- for an analog gain stage: a `<PolesZeros>` stage with empty `<Pole>`s and `<Zero>`s, `<NormalizationFrequency> = None` and `<NormalizationFactor = 1.0>`.  
- for a digital gain stage:  a `<Coefficients>` stage with `<Numerator> = [1.0 ]` and `<Denominator> = []`.  

It would be useful to have a recommended formula for these cases or — even simpler for the user — `<Analog>` and `<Digital>` "filters" with no filter coefficients.  Alternatively, one could remove the requirement of having a `<Filter>` in a `<Stage>`, but this might harm backward-compatibility

Regards,
Wayne Crawford <crawford@ipgp.fr> and Luis Arean <arean@ipgp.fr>

**Comment by crotwell** [comment]
> should be the same for all stages and within the passband, if any

+1 this should also be in the docs for `<StageGain>` and all the frequencies should be the same, if possible.

I am always leery of using a special value to mean "don't know" or "doesn't matter" if that value could actually be legitimately used. In particular, zero frequency is a real frequency, and so it is technically possible to have a meaningful gain at zero frequency for a response that has a frequency dependence. Take a normal low pass filter for example, there is a true gain at f=0 and it does have a frequency dependence, both ripple in the pass band and of course a steep dropoff above the cutoff frequency. 

If a "doesn't matter" frequency value is to be used, then something like -1 avoids the confusion with a real value. On the other hand, if it really doesn't matter, then using the frequency from the previous and/or following stages would be easier on clients. It would require a new major version, but making the frequency element optional, or introducing a `<NoFrequencyDependency>` element would more meaningfully convey "doesn't matter" imho. 

See also #22 for stages with no frequency response, but of course it would require a major revision to stationxml as it would be a new element. Basically something is still needed to hold input and output units for the stage. I think what you are doing currently is completely reasonable, but would be nice if it was standardized.

**Comment by chad-iris** [comment]
Regarding the recommendation alignment of frequencies over all stages, at IRIS we are starting to deviate from that recommendation.

To explain, with details from @metempleton: The gain of FIR filters is defined as equal to the sum of their coefficients at DC; this is the most accurate way to document the gain of a FIR filter, all other gains are a calculated estimate.  Further, the gain and normalization of sensors, and other equipment, is likely measured at specific frequencies chosen by manufacturers; these are the most accurate and trusted values, all others are estimates based on that measurement.  The rationale is to retain these most accurate values to documented the response stages, even if they are not aligned.

If memory serves, the alignment of frequencies is not required for response calculations, but mostly a convenience to support an easy internal sanity check that the total sensitivity matches the product of stage gains.

**Comment by crotwell** [comment]
PR #118 addresses stage filter frequencies

**Comment by crotwell** [comment]
PR #120 addresses gain-only stage filters

**Comment by crotwell** [comment]
In PR #120, I said a single numerator FIR was preferred for a gain only stage. But due to the IRIS NRL not using FIR elements, I suspect most current cases of gain-only stages use a Coefficients filter with one numerator and no denominators. The FIR is simpler, but maybe Coefficients would be better to be more compatible with current usage?

**Comment by crotwell** [comment]
I have merged #118 and #120 that fix 2/3 of this.

I fixed a double negative and did a little rearranging for #118, merged, but would be good to reread.

Closing this issue, but opening new one to track just the decimation offset, delay and correction documentation part. See #133
