### ISSUE TITLE
Minor potential text issue in subsource codes (first table)

### ISSUE THREAD

**Issue by kaestli** [FDSN/StationXML#62]
If triaxial channels (A,B,C) are (in contrary to 1,2,3) allowed to be non-orthogonal, then they probably cannot be described as coinciding with the edges of a cube (which is, afaiu, orthogonal by definition). If A,B,C are meant to be orthogonal as well, then i don't understand the difference to 1,2,3.

**Comment by crotwell** [comment]
@kaestli can you point out the section where you see this? Maybe you are looking at the FDSN Source Identifiers spec instead of this one?
