### ISSUE TITLE
DOC: Add section with deprecation warnings

### ISSUE THREAD

**Issue by petrrr** [FDSN/StationXML#63]
In the current documentation of Station XML there are some deprecation warnings for some (currently few) elements. 

I would suggest to group all these deprecation warnings and possibly also other upcoming/expected changes, like switch from `required` <-> `non required`, count rules, etc. in a dedicated section. This would help new with new implementations.

**Comment by crotwell** [comment]
fixed in #92 

see section 1.4.2
Overview / StationXML Schema Changes / Potential Future Changes
