### ISSUE TITLE
fdsn source-identifiers

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#65]
Incorporate the new FDSN source-identifiers into stationXML, perhaps either as a new attribute on network/station/channel, or within the existing Identifier elements.

http://docs.fdsn.org/projects/source-identifiers/en/v1.0/

**Comment by chad-iris** [comment]
The `BaseNodeType` used for `Network`, `Station`, and `Channel` elements, includes a `sourceID` attribute that is intended for the now-approved FDSN Source Identifiers.

Closing for now, but re-open if you think this is insufficient.

**Comment by crotwell** [comment]
+1

Would be nice if it was in the docs.
