### ISSUE TITLE
Recommend FDSN Source Identifiers and use as examples for sourceID attribute

### ISSUE THREAD

**Issue by chad-iris** [FDSN/StationXML#67]
The `sourceID` parameter (BaseNodeType used for `Network`, `Station`, and `Channel`) should recommend the FDSN Source Identifiers: http://docs.fdsn.org/projects/source-identifiers/en/v1.0/

Example:
http://docs.fdsn.org/projects/stationxml/en/latest/reference.html?highlight=sourceID#network-required

**Comment by crotwell** [comment]
fix in PR #87
