### ISSUE TITLE
Documentation for <ResponseList> has switched definitions of InputUnits and OutputUnits

### ISSUE THREAD

**Issue by peacocks** [FDSN/StationXML#69]
http://docs.fdsn.org/projects/stationxml/en/latest/reference.html#response-stage-responselist-inputunits - the description of "InputUnits" looks as if it should be the description of "OutputUnits": 
"The units of the data as input from the perspective of data acquisition. After correcting data for this response, these would be the resulting units."
And the description of "OutputUnits" looks as if it belongs with "InputUnits":
"The units of the data as output from the perspective of data acquisition. These would be the units of the data prior to correcting for this response."

**Comment by crotwell** [comment]
Description is confusing, but I think correct. Would be good to remove the "correcting for" sentence and replace it with an example, perhaps something like:

> For stage 1 of a seismometer, InputUnits would be 'm/s' and OutputUnits would be 'v'.

**Comment by crotwell** [comment]
I have updated the text in PR #91 

@peacocks does this look good to you?

**Comment by peacocks** [comment]
I can't find the corrected version - sorry - looking in https://github.com/crotwell/StationXML/blob/responselist_units/docs/level-response.rst

I realise that my description of the problem was not very clear.  The descriptions of "InputUnits" and "OutputUnits" in the original both consist of two sentences.  The first sentence is correct for both descriptions; my original point was to wonder whether the second sentence should be interchanged between the two descriptions, so they would read:

for _InputUnits_: The units of the data as input from the perspective of data acquisition. The units of the data as input from the perspective of data acquisition.

for _OutputUnits_: The units of the data as output from the perspective of data acquisition. After correcting data for this response, these would be the resulting units. 

But of course an example would make it clear for both.

(Sorry for delay in replying - finally got a vacation!)

**Comment by crotwell** [comment]
You can see the changes within the pull request here:
https://github.com/FDSN/StationXML/pull/91/files
We do not have html generated for each pull request.

Do these changes look ok to you?

**Comment by jschaeff** [comment]
Do we wait for @peacocks validation ? I feel the changes make the doc clearer now.

**Comment by crotwell** [comment]
No, nice to have @peacocks validation but we can proceed if the eval team agrees.

**Comment by PetrColinSky** [comment]
It is clear now, yes. I also found it super-confusing originally.
