### ISSUE TITLE
ASCII vs Unicode in stationxml

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#93]
Would be useful to document whether unicode is allowed in stationxml. 

Seems like UTF-8 should be the preferred encoding and unicode should be allowed in textual descriptions to respect non-engligh languages.

But unit names are a place where it may be less desirable for ease of parsing. Example in SI multiplication is the "half-high (centred) dot (⋅)", which could be unicode U+00B7 or U+22C5. Also degree symbol for degree Celcius could be U+00B0 or U+2103. Use of these unicode characters might be technically more correct, but would also be harder to parse. Allowing unicode in the unit descriptions on the other hand seems reasonable.

**Comment by PetrColinSky** [comment]
This is bit on the edge of my skills to comment on encoding. I am on for any clarification which makes things more clear and avoids any ambiguity. UTF-8 looks good to me as a general standard.

**Comment by chad-iris** [comment]
Default encoding for XML is UTF-8, so that's definitely the way to go.

Given that users will be converting to SEED, and thus ASCII, for a while yet, I suggest that it would be valuable to have a statement along the lines of "use ASCII when possible for maximum portability".

**Comment by rcasey-iris** [comment]
When it comes to StationXML, the cat is already out of the bag as far as UTF-8 being in use.  The area that we (IRIS) have had the most issue with are accent characters on the names for people and places.  The UTF-8 encodings load seamlessly into our database and transfer out correctly in kind.  It's clients that can struggle with the retrieved output if their default behavior is to read ASCII, so we've been moving to explicit indication of UTF-8 for our character set in metadata output.

**Comment by crotwell** [comment]
Added a section about UTF-8 in PR #108
